version: '2'

services:
  db:
    container_name: db
    image: 'postgres'
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    env_file:
      - '.env_docker'
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"

  api:
    container_name: api
    depends_on:
      - 'db'
    build:
      dockerfile: Dockerfile
      context: .
    command: bundle exec puma -C config/puma.rb
    ports:
      - '3000:3000'
    volumes:
      - '.:/worker-management'
      - 'bundle:/usr/local/bundle'
    env_file:
      - '.env_docker'

volumes:
  postgres:
  bundle:
    driver: local